import AppKit
import Foundation
import SQLite3

let projectStatusOptions = [
    "draft",
    "prd_uploaded",
    "prd_analyzed",
    "team_selected",
    "task_generated",
    "in_progress",
    "review",
    "demo_ready",
    "demo_sent",
    "revision",
    "handoff_ready",
    "closed",
    "archived"
]

let taskStatusOptions = [
    "todo",
    "assigned",
    "awaiting_approval",
    "launch_blocked",
    "running",
    "review",
    "audit",
    "need_fix",
    "blocked",
    "cancelled",
    "done"
]

let taskPrimaryStageOptions = ["open", "in_progress", "review", "audit", "done"]
let priorityOptions = ["low", "medium", "high"]
let skillTypeOptions = ["prompt", "tool", "workflow", "output", "review", "audit"]

struct PRDImportResult {
    let sourcePath: String
    let copiedPath: String
    let normalizedPath: String
    let analysisPath: String
    let generatedArtifactPaths: [String]
}

struct ProjectWorkspaceHealthReport: Hashable {
    let projectRootPath: String
    let rootExists: Bool
    let existingFolders: [String]
    let missingFolders: [String]
    let readmeExists: Bool

    var totalRequiredFolders: Int { StudioPaths.folderTemplate.count }
    var existingFolderCount: Int { existingFolders.count }
    var isHealthy: Bool { rootExists && missingFolders.isEmpty }
}

enum StudioPaths {
    static let defaultProjectsRoot = "~/AgentStudio/Projects"
    static let folderTemplate = [
        "00_Input",
        "01_PRD",
        "02_PRD_Analysis",
        "03_Taskmaster",
        "04_Teams",
        "05_Current_Task",
        "06_Runs",
        "07_Reviews",
        "08_Audits",
        "09_Requests",
        "10_Demo",
        "11_Handoff",
        "12_Archive"
    ]

    static func expanded(_ path: String) -> String {
        (path as NSString).expandingTildeInPath
    }

    static func treePreview(rootName: String = "{project-slug}") -> String {
        var lines = ["~/AgentStudio/Projects/\(rootName)/"]
        for (index, folder) in folderTemplate.enumerated() {
            let prefix = index == folderTemplate.count - 1 ? "└──" : "├──"
            lines.append("\(prefix) \(folder)/")
        }
        return lines.joined(separator: "\n")
    }
}

enum AppDialogs {
    @MainActor
    static func chooseFolder() -> URL? {
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = false
        panel.canCreateDirectories = true
        panel.prompt = "Choose Folder"
        return panel.runModal() == .OK ? panel.url : nil
    }

    @MainActor
    static func choosePRDFile() -> URL? {
        let panel = NSOpenPanel()
        panel.canChooseDirectories = false
        panel.canChooseFiles = true
        panel.allowsMultipleSelection = false
        panel.prompt = "Import PRD"
        return panel.runModal() == .OK ? panel.url : nil
    }

    @MainActor
    static func openInFinder(path: String) {
        let expanded = StudioPaths.expanded(path)
        NSWorkspace.shared.open(URL(fileURLWithPath: expanded))
    }
}

enum Slugifier {
    static func slug(from input: String) -> String {
        let lowered = input.lowercased()
        let pattern = "[^a-z0-9]+"
        let regex = try? NSRegularExpression(pattern: pattern)
        let range = NSRange(location: 0, length: lowered.utf16.count)
        let hyphenated = regex?.stringByReplacingMatches(in: lowered, options: [], range: range, withTemplate: "-") ?? lowered
        return hyphenated.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
    }
}

enum FolderGeneratorService {
    static func createProjectFolders(for project: StudioProject) throws -> String {
        let fileManager = FileManager.default
        let basePath = StudioPaths.expanded(project.baseFolderPath)
        let projectRoot = URL(fileURLWithPath: basePath, isDirectory: true)
            .appendingPathComponent(project.slug, isDirectory: true)

        try fileManager.createDirectory(at: projectRoot, withIntermediateDirectories: true)
        for folder in StudioPaths.folderTemplate {
            try fileManager.createDirectory(
                at: projectRoot.appendingPathComponent(folder, isDirectory: true),
                withIntermediateDirectories: true
            )
        }

        let bootstrapReadme = projectRoot.appendingPathComponent("README.md")
        if !fileManager.fileExists(atPath: bootstrapReadme.path) {
            let content = "# \(project.name)\n\nGenerated by Head Office Agent Studio.\n\nStatus: \(project.status)\n"
            try content.write(to: bootstrapReadme, atomically: true, encoding: .utf8)
        }

        return projectRoot.path
    }

    static func workspaceHealth(for project: StudioProject) -> ProjectWorkspaceHealthReport {
        let fileManager = FileManager.default
        let projectRootPath = resolvedProjectRootPath(for: project)
        let projectRoot = URL(fileURLWithPath: projectRootPath, isDirectory: true)
        let rootExists = fileManager.fileExists(atPath: projectRoot.path)

        var existingFolders: [String] = []
        var missingFolders: [String] = []

        for folder in StudioPaths.folderTemplate {
            let folderPath = projectRoot.appendingPathComponent(folder, isDirectory: true).path
            var isDirectory: ObjCBool = false
            if fileManager.fileExists(atPath: folderPath, isDirectory: &isDirectory), isDirectory.boolValue {
                existingFolders.append(folder)
            } else {
                missingFolders.append(folder)
            }
        }

        let readmeExists = fileManager.fileExists(atPath: projectRoot.appendingPathComponent("README.md").path)

        return ProjectWorkspaceHealthReport(
            projectRootPath: projectRoot.path,
            rootExists: rootExists,
            existingFolders: existingFolders,
            missingFolders: missingFolders,
            readmeExists: readmeExists
        )
    }

    @discardableResult
    static func repairProjectFolders(for project: StudioProject) throws -> ProjectWorkspaceHealthReport {
        let fileManager = FileManager.default
        let projectRoot = URL(fileURLWithPath: resolvedProjectRootPath(for: project), isDirectory: true)

        try fileManager.createDirectory(at: projectRoot, withIntermediateDirectories: true)
        for folder in StudioPaths.folderTemplate {
            try fileManager.createDirectory(
                at: projectRoot.appendingPathComponent(folder, isDirectory: true),
                withIntermediateDirectories: true
            )
        }

        let bootstrapReadme = projectRoot.appendingPathComponent("README.md")
        if !fileManager.fileExists(atPath: bootstrapReadme.path) {
            let content = "# \(project.name)\n\nGenerated by Head Office Agent Studio.\n\nStatus: \(project.status)\n"
            try content.write(to: bootstrapReadme, atomically: true, encoding: .utf8)
        }

        return workspaceHealth(for: project)
    }

    private static func resolvedProjectRootPath(for project: StudioProject) -> String {
        if !project.createdFolderPath.isEmpty {
            return StudioPaths.expanded(project.createdFolderPath)
        }

        return URL(fileURLWithPath: StudioPaths.expanded(project.baseFolderPath), isDirectory: true)
            .appendingPathComponent(project.slug, isDirectory: true)
            .path
    }
}

enum PRDImportService {
    static func importPRD(from sourceURL: URL, into project: StudioProject) throws -> PRDImportResult {
        guard !project.createdFolderPath.isEmpty else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 1, userInfo: [NSLocalizedDescriptionKey: "Project folder has not been created yet."])
        }

        let fileManager = FileManager.default
        let projectRoot = URL(fileURLWithPath: project.createdFolderPath, isDirectory: true)
        let prdDirectory = projectRoot.appendingPathComponent("01_PRD", isDirectory: true)
        let analysisDirectory = projectRoot.appendingPathComponent("02_PRD_Analysis", isDirectory: true)

        try fileManager.createDirectory(at: prdDirectory, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: analysisDirectory, withIntermediateDirectories: true)

        let ext = sourceURL.pathExtension.isEmpty ? "txt" : sourceURL.pathExtension
        let copiedURL = prdDirectory.appendingPathComponent("PRD_ORIGINAL.\(ext)")
        if fileManager.fileExists(atPath: copiedURL.path) {
            try fileManager.removeItem(at: copiedURL)
        }
        try fileManager.copyItem(at: sourceURL, to: copiedURL)

        let normalizedURL = prdDirectory.appendingPathComponent("PRD_NORMALIZED.md")
        let importLogURL = prdDirectory.appendingPathComponent("PRD_IMPORT_LOG.md")
        let analysisURL = analysisDirectory.appendingPathComponent("PRD_ANALYSIS.md")
        let missingInfoURL = analysisDirectory.appendingPathComponent("MISSING_INFO.md")
        let scopeSummaryURL = analysisDirectory.appendingPathComponent("SCOPE_SUMMARY.md")
        let moduleMapURL = analysisDirectory.appendingPathComponent("MODULE_MAP.md")
        let roleMapURL = analysisDirectory.appendingPathComponent("ROLE_MAP.md")
        let riskReportURL = analysisDirectory.appendingPathComponent("RISK_REPORT.md")
        let checklistURL = analysisDirectory.appendingPathComponent("ANALYST_CHECKLIST.md")

        let normalizedMarkdown = normalizePRD(sourceURL: sourceURL)
        try normalizedMarkdown.write(to: normalizedURL, atomically: true, encoding: .utf8)

        let previewLines = normalizedMarkdown
            .components(separatedBy: .newlines)
            .filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
        let summaryParagraphs = Array(previewLines.prefix(12))
        let extractedRoles = detectRoles(in: normalizedMarkdown)
        let extractedModules = detectModules(in: normalizedMarkdown)
        let extractedRisks = detectRiskLines(in: normalizedMarkdown)

        let importLog = """
        # PRD Import Log

        - Source: \(sourceURL.path)
        - Imported At: \(DateFormatter.studioTimestamp.string(from: .now))
        - Original Copy: \(copiedURL.path)
        - Normalized Markdown: \(normalizedURL.path)
        - Generated Analysis Files:
          - \(analysisURL.lastPathComponent)
          - \(missingInfoURL.lastPathComponent)
          - \(scopeSummaryURL.lastPathComponent)
          - \(moduleMapURL.lastPathComponent)
          - \(roleMapURL.lastPathComponent)
          - \(riskReportURL.lastPathComponent)
          - \(checklistURL.lastPathComponent)
        - Notes: V1 import flow is local-first with extracted text + structured analysis scaffolding.
        """
        try importLog.write(to: importLogURL, atomically: true, encoding: .utf8)

        let analysisStub = """
        # PRD Analysis

        ## Project Summary
        - Source file: \(sourceURL.lastPathComponent)
        - Imported into project: \(project.name)
        - Generated at: \(DateFormatter.studioTimestamp.string(from: .now))

        ## Preview
        \(summaryParagraphs.isEmpty ? "- No preview text extracted." : summaryParagraphs.map { "- \($0)" }.joined(separator: "\n"))

        ## Recommended Next Step
        - Review `SCOPE_SUMMARY.md`, `MODULE_MAP.md`, and `ROLE_MAP.md` before task breakdown.
        - Resolve open items from `MISSING_INFO.md`.
        - Confirm risks in `RISK_REPORT.md` before team assignment.
        """
        try analysisStub.write(to: analysisURL, atomically: true, encoding: .utf8)

        let missingInfo = """
        # Missing Information

        - Confirm the target runtime implementation boundary after Milestone 5.
        - Confirm whether the source PRD is the latest approved version.
        - Confirm external integrations, credentials, and deployment constraints if referenced.
        - Confirm acceptance criteria for any feature phrased only as goals/outcomes.
        - Confirm out-of-scope items explicitly before downstream task generation.
        """
        try missingInfo.write(to: missingInfoURL, atomically: true, encoding: .utf8)

        let scopeSummary = """
        # Scope Summary

        ## Source
        - File: \(sourceURL.lastPathComponent)
        - Project: \(project.name)

        ## Extracted Preview
        \(summaryParagraphs.isEmpty ? "- No preview text extracted." : summaryParagraphs.map { "- \($0)" }.joined(separator: "\n"))

        ## Delivery Focus
        - Parse requirements into modules, roles, acceptance criteria, and risks.
        - Keep the output local-first and file-transparent.
        - Use this artifact as the bridge into task planning.
        """
        try scopeSummary.write(to: scopeSummaryURL, atomically: true, encoding: .utf8)

        let moduleMap = """
        # Module Map

        \(extractedModules.isEmpty ? "- No explicit modules auto-detected. Review PRD manually and add module sections here." : extractedModules.map { "- \($0)" }.joined(separator: "\n"))
        """
        try moduleMap.write(to: moduleMapURL, atomically: true, encoding: .utf8)

        let roleMap = """
        # Role Map

        \(extractedRoles.isEmpty ? "- No explicit user roles auto-detected. Add personas / actors after review." : extractedRoles.map { "- \($0)" }.joined(separator: "\n"))
        """
        try roleMap.write(to: roleMapURL, atomically: true, encoding: .utf8)

        let riskReport = """
        # Risk Report

        ## Auto-detected Signals
        \(extractedRisks.isEmpty ? "- No explicit risk keywords detected. Manual review still required." : extractedRisks.map { "- \($0)" }.joined(separator: "\n"))

        ## Default Milestone Risks
        - Source extraction quality may vary by document type.
        - Binary files still require manual validation even after text extraction.
        - Runtime execution stays out of scope until the post-M5 runtime milestone.
        """
        try riskReport.write(to: riskReportURL, atomically: true, encoding: .utf8)

        let checklist = """
        # Analyst Checklist

        - [ ] Review `PRD_NORMALIZED.md` for extraction quality
        - [ ] Confirm feature list and acceptance criteria
        - [ ] Confirm user roles / actors
        - [ ] Confirm integrations and external dependencies
        - [ ] Review `MISSING_INFO.md` and resolve unknowns
        - [ ] Review `RISK_REPORT.md` before planning
        - [ ] Approve task breakdown input package
        """
        try checklist.write(to: checklistURL, atomically: true, encoding: .utf8)

        let generatedArtifacts = [
            analysisURL.path,
            missingInfoURL.path,
            scopeSummaryURL.path,
            moduleMapURL.path,
            roleMapURL.path,
            riskReportURL.path,
            checklistURL.path
        ]

        return PRDImportResult(
            sourcePath: sourceURL.path,
            copiedPath: copiedURL.path,
            normalizedPath: normalizedURL.path,
            analysisPath: analysisURL.path,
            generatedArtifactPaths: generatedArtifacts
        )
    }

    private static func normalizePRD(sourceURL: URL) -> String {
        let ext = sourceURL.pathExtension.lowercased()
        let header = "# Normalized PRD\n\nImported from: \(sourceURL.lastPathComponent)\n\n"

        if ["md", "markdown", "txt"].contains(ext),
           let content = try? String(contentsOf: sourceURL, encoding: .utf8) {
            return header + content
        }

        if ["html", "htm", "rtf", "doc", "docx"].contains(ext),
           let content = extractUsingTextUtil(sourceURL: sourceURL) {
            return header + content
        }

        if ext == "pdf", let content = extractPDFText(sourceURL: sourceURL) {
            return header + content
        }

        if ext == "html",
           let content = try? String(contentsOf: sourceURL, encoding: .utf8) {
            return header + "```html\n" + content + "\n```\n"
        }

        return header + """
        This file type requires manual review in V1.

        - Original path: \(sourceURL.path)
        - Extension: \(ext.isEmpty ? "unknown" : ext)
        - Action: open the original file and paste/extract the important sections into this markdown file.
        """
    }

    private static func extractUsingTextUtil(sourceURL: URL) -> String? {
        runProcess(executable: "/usr/bin/textutil", arguments: ["-convert", "txt", "-stdout", sourceURL.path])
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nonEmpty
    }

    private static func extractPDFText(sourceURL: URL) -> String? {
        let script = """
from pypdf import PdfReader
import sys
reader = PdfReader(sys.argv[1])
chunks = []
for page in reader.pages:
    chunks.append(page.extract_text() or '')
print('\\n'.join(chunks))
"""
        return runProcess(executable: "/usr/bin/python3", arguments: ["-c", script, sourceURL.path])
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nonEmpty
    }

    private static func runProcess(executable: String, arguments: [String]) -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments

        let outputPipe = Pipe()
        let errorPipe = Pipe()
        process.standardOutput = outputPipe
        process.standardError = errorPipe

        do {
            try process.run()
            process.waitUntilExit()
            let outputData = outputPipe.fileHandleForReading.readDataToEndOfFile()
            let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()
            if process.terminationStatus == 0, let output = String(data: outputData, encoding: .utf8) {
                return output
            }
            if let errorText = String(data: errorData, encoding: .utf8), !errorText.isEmpty {
                return errorText
            }
        } catch {
            return ""
        }

        return ""
    }

    private static func detectRoles(in text: String) -> [String] {
        detectMatches(in: text, keywords: ["admin", "manager", "staff", "user", "client", "operator", "customer", "owner", "agent"])
    }

    private static func detectModules(in text: String) -> [String] {
        let headings = text
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { $0.hasPrefix("#") || $0.lowercased().hasPrefix("module") || $0.lowercased().hasPrefix("feature") }
        return Array(NSOrderedSet(array: headings)) as? [String] ?? []
    }

    private static func detectRiskLines(in text: String) -> [String] {
        text
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter {
                let lower = $0.lowercased()
                return !lower.isEmpty && (lower.contains("risk") || lower.contains("block") || lower.contains("dependency") || lower.contains("assumption"))
            }
    }

    private static func detectMatches(in text: String, keywords: [String]) -> [String] {
        let lines = text.components(separatedBy: .newlines)
        var matches: [String] = []
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            let lower = trimmed.lowercased()
            guard !trimmed.isEmpty else { continue }
            if keywords.contains(where: { lower.contains($0) }) {
                matches.append(trimmed)
            }
        }
        return Array(NSOrderedSet(array: matches)) as? [String] ?? []
    }
}

private extension String {
    var nonEmpty: String? {
        let trimmed = trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }
}

final class SQLiteJSONStore {
    private var db: OpaquePointer?
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()
    private let databaseURL: URL

    init() throws {
        let supportDirectory = try Self.makeSupportDirectory()
        databaseURL = supportDirectory.appendingPathComponent("HeadOfficeAgentStudio.sqlite")
        try openDatabase()
        try createSchema()
        encoder.dateEncodingStrategy = .iso8601
        decoder.dateDecodingStrategy = .iso8601
    }

    deinit {
        sqlite3_close(db)
    }

    func loadAll<Record: StudioRecord>(_ type: Record.Type) throws -> [Record] {
        let query = "SELECT payload FROM records WHERE type = ? ORDER BY updated_at DESC;"
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, query, -1, &statement, nil) == SQLITE_OK else {
            throw databaseError(message: "Failed to prepare load statement")
        }
        defer { sqlite3_finalize(statement) }

        sqlite3_bind_text(statement, 1, Record.recordType, -1, SQLITE_TRANSIENT)

        var results: [Record] = []
        while sqlite3_step(statement) == SQLITE_ROW {
            guard let text = sqlite3_column_text(statement, 0) else { continue }
            let payload = String(cString: text)
            let data = Data(payload.utf8)
            results.append(try decoder.decode(Record.self, from: data))
        }
        return results
    }

    func save<Record: StudioRecord>(_ record: Record) throws {
        let query = "INSERT INTO records(type, id, payload, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT(type, id) DO UPDATE SET payload = excluded.payload, updated_at = excluded.updated_at;"
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, query, -1, &statement, nil) == SQLITE_OK else {
            throw databaseError(message: "Failed to prepare save statement")
        }
        defer { sqlite3_finalize(statement) }

        let payloadData = try encoder.encode(record)
        let payload = String(decoding: payloadData, as: UTF8.self)

        sqlite3_bind_text(statement, 1, Record.recordType, -1, SQLITE_TRANSIENT)
        sqlite3_bind_text(statement, 2, record.id.uuidString, -1, SQLITE_TRANSIENT)
        sqlite3_bind_text(statement, 3, payload, -1, SQLITE_TRANSIENT)
        sqlite3_bind_double(statement, 4, Date().timeIntervalSince1970)

        guard sqlite3_step(statement) == SQLITE_DONE else {
            throw databaseError(message: "Failed to save record")
        }
    }

    func delete<Record: StudioRecord>(_ record: Record) throws {
        let query = "DELETE FROM records WHERE type = ? AND id = ?;"
        var statement: OpaquePointer?
        guard sqlite3_prepare_v2(db, query, -1, &statement, nil) == SQLITE_OK else {
            throw databaseError(message: "Failed to prepare delete statement")
        }
        defer { sqlite3_finalize(statement) }

        sqlite3_bind_text(statement, 1, Record.recordType, -1, SQLITE_TRANSIENT)
        sqlite3_bind_text(statement, 2, record.id.uuidString, -1, SQLITE_TRANSIENT)

        guard sqlite3_step(statement) == SQLITE_DONE else {
            throw databaseError(message: "Failed to delete record")
        }
    }

    private func openDatabase() throws {
        guard sqlite3_open(databaseURL.path, &db) == SQLITE_OK else {
            throw databaseError(message: "Unable to open SQLite database at \(databaseURL.path)")
        }
    }

    private func createSchema() throws {
        let schema = """
        CREATE TABLE IF NOT EXISTS records (
            type TEXT NOT NULL,
            id TEXT NOT NULL,
            payload TEXT NOT NULL,
            updated_at REAL NOT NULL,
            PRIMARY KEY (type, id)
        );
        """
        guard sqlite3_exec(db, schema, nil, nil, nil) == SQLITE_OK else {
            throw databaseError(message: "Unable to create records table")
        }
    }

    private func databaseError(message: String) -> NSError {
        let details = db.flatMap { sqlite3_errmsg($0) }.map { String(cString: $0) } ?? "Unknown SQLite error"
        return NSError(domain: "HeadOfficeAgentStudio.SQLite", code: 1, userInfo: [NSLocalizedDescriptionKey: "\(message): \(details)"])
    }

    private static func makeSupportDirectory() throws -> URL {
        let support = try FileManager.default.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        let directory = support.appendingPathComponent("HeadOfficeAgentStudio", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }
}

private let SQLITE_TRANSIENT = unsafeBitCast(-1, to: sqlite3_destructor_type.self)

@MainActor
final class StudioStore: ObservableObject {
    @Published var projects: [StudioProject] = []
    @Published var agents: [AgentDefinition] = []
    @Published var skills: [SkillDefinition] = []
    @Published var teams: [TeamDefinition] = []
    @Published var runtimes: [RuntimeProfile] = []
    @Published var tasks: [StudioTask] = []
    @Published var runLogs: [TaskRunLog] = []
    @Published var humanRequests: [HumanRequestItem] = []
    @Published var demoItems: [DemoHandoffItem] = []
    @Published var bootstrapMessage = ""

    private let database: SQLiteJSONStore?

    init() {
        let initializedDatabase: SQLiteJSONStore?
        var initialMessage = ""

        do {
            initializedDatabase = try SQLiteJSONStore()
            initialMessage = "SQLite store ready"
        } catch {
            initializedDatabase = nil
            initialMessage = error.localizedDescription
        }

        self.database = initializedDatabase
        self.bootstrapMessage = initialMessage
        reloadAll()
        try? seedIfNeeded()
    }

    func reloadAll() {
        guard let database else { return }
        projects = ((try? database.loadAll(StudioProject.self)) ?? []).sorted { $0.updatedAt > $1.updatedAt }
        agents = ((try? database.loadAll(AgentDefinition.self)) ?? []).sorted { $0.name < $1.name }
        skills = ((try? database.loadAll(SkillDefinition.self)) ?? []).sorted { $0.name < $1.name }
        teams = ((try? database.loadAll(TeamDefinition.self)) ?? []).sorted { $0.name < $1.name }
        runtimes = ((try? database.loadAll(RuntimeProfile.self)) ?? []).sorted { $0.name < $1.name }
        tasks = ((try? database.loadAll(StudioTask.self)) ?? []).sorted { $0.createdAt < $1.createdAt }
        runLogs = ((try? database.loadAll(TaskRunLog.self)) ?? []).sorted { $0.startedAt > $1.startedAt }
        humanRequests = ((try? database.loadAll(HumanRequestItem.self)) ?? []).sorted { $0.createdAt > $1.createdAt }
        demoItems = ((try? database.loadAll(DemoHandoffItem.self)) ?? []).sorted { $0.createdAt < $1.createdAt }
    }

    func createProject(
        name: String,
        projectType: String,
        clientLabel: String,
        deadline: Date,
        priority: String,
        outputGoal: String,
        baseFolderPath: String
    ) throws -> StudioProject {
        let slug = Slugifier.slug(from: name)
        var project = StudioProject(
            name: name,
            slug: slug,
            projectType: projectType,
            clientLabel: clientLabel,
            deadline: deadline,
            priority: priority,
            outputGoal: outputGoal,
            baseFolderPath: baseFolderPath,
            createdFolderPath: "",
            status: "draft",
            currentMilestone: "Project Setup",
            prdOriginalPath: "",
            prdNormalizedPath: "",
            notes: "",
            knownLimitations: nil,
            lastDemoScriptPath: nil,
            lastHandoffChecklistPath: nil,
            lastClosureSummaryPath: nil,
            createdAt: .now,
            updatedAt: .now
        )
        let createdPath = try FolderGeneratorService.createProjectFolders(for: project)
        project.createdFolderPath = createdPath
        project.notes = "Local project structure created. Ready for PRD import."
        try save(project)
        seedDemoAndHandoffChecklist(for: project)
        reloadAll()
        return project
    }

    func importPRD(projectID: UUID, sourceURL: URL) throws -> PRDImportResult {
        guard var project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }
        let result = try PRDImportService.importPRD(from: sourceURL, into: project)
        project.prdOriginalPath = result.copiedPath
        project.prdNormalizedPath = result.normalizedPath
        project.status = "prd_analyzed"
        project.currentMilestone = "PRD Context"
        project.notes = "PRD imported and analysis artifacts generated."
        project.updatedAt = .now
        try save(project)
        seedInitialTaskBoard(for: project)
        reloadAll()
        return result
    }

    func updateProject(
        id: UUID,
        name: String,
        projectType: String,
        clientLabel: String,
        deadline: Date,
        priority: String,
        outputGoal: String,
        notes: String
    ) throws -> StudioProject {
        guard var project = projects.first(where: { $0.id == id }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        project.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        project.projectType = projectType.trimmingCharacters(in: .whitespacesAndNewlines)
        project.clientLabel = clientLabel.trimmingCharacters(in: .whitespacesAndNewlines)
        project.deadline = deadline
        project.priority = priority
        project.outputGoal = outputGoal.trimmingCharacters(in: .whitespacesAndNewlines)
        project.notes = notes.trimmingCharacters(in: .whitespacesAndNewlines)
        project.updatedAt = .now
        try save(project)
        reloadAll()
        return project
    }

    func archiveProject(id: UUID) throws -> StudioProject {
        guard var project = projects.first(where: { $0.id == id }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        project.status = "archived"
        project.currentMilestone = "Archived"
        project.updatedAt = .now
        try save(project)
        reloadAll()
        return project
    }

    func deleteProjectRecord(id: UUID) throws {
        guard let project = projects.first(where: { $0.id == id }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        let relatedTeams = teams.filter { $0.projectSlug == project.slug }
        let relatedTasks = tasks.filter { $0.projectSlug == project.slug }
        let relatedRunLogs = runLogs.filter { $0.projectSlug == project.slug }
        let relatedRequests = humanRequests.filter { $0.projectSlug == project.slug }
        let relatedDemoItems = demoItems.filter { $0.projectSlug == project.slug }

        try delete(project)
        try relatedTeams.forEach { try delete($0) }
        try relatedTasks.forEach { try delete($0) }
        try relatedRunLogs.forEach { try delete($0) }
        try relatedRequests.forEach { try delete($0) }
        try relatedDemoItems.forEach { try delete($0) }
        reloadAll()
    }

    func projectWorkspaceHealth(projectID: UUID) throws -> ProjectWorkspaceHealthReport {
        guard let project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }
        return FolderGeneratorService.workspaceHealth(for: project)
    }

    @discardableResult
    func repairProjectWorkspace(projectID: UUID) throws -> ProjectWorkspaceHealthReport {
        guard var project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        let report = try FolderGeneratorService.repairProjectFolders(for: project)
        if project.createdFolderPath.isEmpty {
            project.createdFolderPath = report.projectRootPath
        }
        project.notes = report.isHealthy
            ? "Workspace folders verified and repaired if needed."
            : "Workspace repair attempted. Missing folders remain: \(report.missingFolders.joined(separator: ", "))"
        project.updatedAt = .now
        try save(project)
        reloadAll()
        return report
    }

    func updateProjectStatus(id: UUID, status: String) {
        if status == "closed" {
            _ = try? attemptCloseProject(projectID: id)
            return
        }

        guard var project = projects.first(where: { $0.id == id }) else { return }
        project.status = status
        project.currentMilestone = milestoneLabel(for: status, fallback: project.currentMilestone)
        project.updatedAt = .now
        try? save(project)
        reloadAll()
    }

    func updateKnownLimitations(projectID: UUID, text: String) {
        guard var project = projects.first(where: { $0.id == projectID }) else { return }
        let cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)
        project.knownLimitations = cleaned.isEmpty ? nil : cleaned
        project.currentMilestone = "Demo / Handoff Readiness"
        project.updatedAt = .now
        try? save(project)

        upsertDemoItem(
            projectSlug: project.slug,
            itemType: "handoff",
            title: "Known limitations",
            details: cleaned.isEmpty ? "No known limitations documented yet." : cleaned,
            owner: "Documentation Agent",
            artifactPath: nil,
            status: cleaned.isEmpty ? "pending" : "done"
        )
        reloadAll()
    }

    func generateDemoScriptTemplate(projectID: UUID) throws -> String {
        guard var project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        let demoDirectory = try artifactDirectory(for: project, folderName: "10_Demo")
        let demoURL = demoDirectory.appendingPathComponent("DEMO_SCRIPT.md")
        let content = """
        # Demo Script — \(project.name)

        ## Goal
        - Show the V1 native macOS shell running locally.
        - Walk from project setup to demo/handoff readiness without autonomous execution.

        ## Suggested Flow
        1. Open the Dashboard and confirm current milestone: \(project.currentMilestone).
        2. Open Create Project and point out the generated workspace at `\(project.createdFolderPath)`.
        3. Open PRD Import and review the copied/normalized PRD paths.
        4. Open Team Builder and Runtime Manager to show assigned roles and planned runtimes.
        5. Open Task Board and move a sample task through manual/mock statuses.
        6. Open Run Log and Human Request Inbox to show traceability.
        7. Open Demo / Handoff Center and review generated artifacts.

        ## Talking Points
        - V1 is local-first and file-transparent.
        - Runtime execution remains manual/mock in this milestone.
        - Closure is gated by blocking human requests.

        ## Demo Notes
        - Client / Owner: \(project.clientLabel)
        - Priority: \(project.priority)
        - Output Goal: \(project.outputGoal)
        """
        try content.write(to: demoURL, atomically: true, encoding: .utf8)

        project.lastDemoScriptPath = demoURL.path
        project.currentMilestone = "Demo / Handoff Readiness"
        if project.status == "draft" || project.status == "prd_uploaded" || project.status == "prd_analyzed" || project.status == "team_selected" || project.status == "task_generated" {
            project.status = "demo_ready"
        }
        project.updatedAt = .now
        try save(project)

        upsertDemoItem(
            projectSlug: project.slug,
            itemType: "demo",
            title: "Demo script",
            details: "Generated demo walkthrough template for the milestone 6 review.",
            owner: "Demo Agent",
            artifactPath: demoURL.path,
            status: "done"
        )
        reloadAll()
        return demoURL.path
    }

    func generateHandoffChecklistTemplate(projectID: UUID) throws -> String {
        guard var project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        let handoffDirectory = try artifactDirectory(for: project, folderName: "11_Handoff")
        let handoffURL = handoffDirectory.appendingPathComponent("HANDOFF_CHECKLIST.md")
        let content = """
        # Handoff Checklist — \(project.name)

        ## Deliverables
        - [ ] Native macOS shell builds from `swift build`
        - [ ] SQLite store created and readable
        - [ ] PRD files copied into project workspace
        - [ ] Demo script reviewed
        - [ ] Known limitations confirmed
        - [ ] Closure summary exported

        ## Paths
        - Project Root: `\(project.createdFolderPath)`
        - PRD Original: `\(project.prdOriginalPath.isEmpty ? "Not imported" : project.prdOriginalPath)`
        - PRD Normalized: `\(project.prdNormalizedPath.isEmpty ? "Not imported" : project.prdNormalizedPath)`
        - Demo Script: `\(project.lastDemoScriptPath ?? "Not generated")`

        ## Limitations
        \(project.knownLimitations ?? "- Runtime execution remains manual/mock in V1.\n- Add project-specific constraints here.")
        """
        try content.write(to: handoffURL, atomically: true, encoding: .utf8)

        project.lastHandoffChecklistPath = handoffURL.path
        project.currentMilestone = "Demo / Handoff Readiness"
        project.updatedAt = .now
        try save(project)

        upsertDemoItem(
            projectSlug: project.slug,
            itemType: "handoff",
            title: "Handoff checklist",
            details: "Generated handoff checklist template for milestone 6 packaging.",
            owner: "Handoff Agent",
            artifactPath: handoffURL.path,
            status: "done"
        )
        reloadAll()
        return handoffURL.path
    }

    func exportClosureSummary(projectID: UUID) throws -> String {
        guard var project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        let handoffDirectory = try artifactDirectory(for: project, folderName: "11_Handoff")
        let closureURL = handoffDirectory.appendingPathComponent("CLOSURE_SUMMARY.md")
        let projectTasks = tasks.filter { $0.projectSlug == project.slug }
        let openTasks = projectTasks.filter { $0.status != "done" }
        let blocking = blockingRequests(for: project.slug)
        let recentLogs = runLogs.filter { $0.projectSlug == project.slug }.prefix(5)
        let projectDemoItems = demoItems.filter { $0.projectSlug == project.slug }

        let demoChecklist = projectDemoItems.map { item in
            let artifactNote = item.artifactPath.map { " (`\($0)` )" } ?? ""
            return "- [\(item.status == "done" ? "x" : " ")] \(item.title) — \(item.status)\(artifactNote)"
        }.joined(separator: "\n")

        let openTaskLines = openTasks.isEmpty
            ? "- None"
            : openTasks.map { "- \($0.taskCode): \($0.title) [\($0.status)]" }.joined(separator: "\n")

        let blockingLines = blocking.isEmpty
            ? "- None"
            : blocking.map { "- \($0.title) [\($0.status)] — \($0.need)" }.joined(separator: "\n")

        let recentLogLines = recentLogs.isEmpty
            ? "- None"
            : recentLogs.map { "- \($0.taskCode) / \($0.status): \($0.summary)" }.joined(separator: "\n")

        let content = """
        # Closure Summary — \(project.name)

        ## Project Snapshot
        - Status: \(project.status)
        - Milestone: \(project.currentMilestone)
        - Client / Owner: \(project.clientLabel)
        - Deadline: \(DateFormatter.studioDate.string(from: project.deadline))
        - Generated At: \(DateFormatter.studioTimestamp.string(from: .now))

        ## Artifact Paths
        - Project Root: `\(project.createdFolderPath)`
        - Demo Script: `\(project.lastDemoScriptPath ?? "Not generated")`
        - Handoff Checklist: `\(project.lastHandoffChecklistPath ?? "Not generated")`
        - PRD Normalized: `\(project.prdNormalizedPath.isEmpty ? "Not imported" : project.prdNormalizedPath)`

        ## Known Limitations
        \(project.knownLimitations ?? "- Runtime execution remains manual/mock in V1.")

        ## Demo / Handoff Items
        \(demoChecklist.isEmpty ? "- None" : demoChecklist)

        ## Open Tasks
        \(openTaskLines)

        ## Blocking Requests
        \(blockingLines)

        ## Recent Run Log Highlights
        \(recentLogLines)
        """
        try content.write(to: closureURL, atomically: true, encoding: .utf8)

        project.lastClosureSummaryPath = closureURL.path
        project.currentMilestone = "Demo / Handoff Readiness"
        project.updatedAt = .now
        try save(project)

        upsertDemoItem(
            projectSlug: project.slug,
            itemType: "handoff",
            title: "Closure package",
            details: "Closure summary exported with current open tasks, requests, and artifact paths.",
            owner: "Handoff Agent",
            artifactPath: closureURL.path,
            status: blocking.isEmpty ? "done" : "in_progress"
        )
        reloadAll()
        return closureURL.path
    }

    func attemptCloseProject(projectID: UUID) throws -> String {
        guard let project = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found"])
        }

        let blocking = blockingRequests(for: project.slug)
        guard blocking.isEmpty else {
            return "Cannot close project while \(blocking.count) blocking requests remain open."
        }

        let closurePath = try exportClosureSummary(projectID: projectID)
        guard var refreshedProject = projects.first(where: { $0.id == projectID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 500, userInfo: [NSLocalizedDescriptionKey: "Project refresh failed after closure export"])
        }

        refreshedProject.status = "closed"
        refreshedProject.currentMilestone = "Closed"
        refreshedProject.lastClosureSummaryPath = closurePath
        refreshedProject.updatedAt = .now
        try save(refreshedProject)

        upsertDemoItem(
            projectSlug: refreshedProject.slug,
            itemType: "handoff",
            title: "Project closure gate",
            details: "Project closed after closure summary export and zero blocking requests.",
            owner: "Handoff Agent",
            artifactPath: closurePath,
            status: "done"
        )
        reloadAll()
        return "Project \(project.name) closed. Closure summary exported to \(closurePath)"
    }

    func prepareRuntimeBrief(taskID: UUID) throws -> String {
        guard var task = tasks.first(where: { $0.id == taskID }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Task not found"])
        }
        guard let project = projects.first(where: { $0.slug == task.projectSlug }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Project not found for task \(task.taskCode)"])
        }

        let runtime = runtimes.first(where: { $0.name == task.runtimeName })
        let currentTaskDirectory = try artifactDirectory(for: project, folderName: "05_Current_Task")
        let runDirectory = try artifactDirectory(for: project, folderName: "06_Runs")
        let requestDirectory = try artifactDirectory(for: project, folderName: "09_Requests")
        let fileStamp = DateFormatter.studioFileStamp.string(from: .now)
        let briefURL = currentTaskDirectory.appendingPathComponent("TASK_BRIEF.md")
        let stdoutURL = runDirectory.appendingPathComponent("\(fileStamp)-stdout.log")
        let stderrURL = runDirectory.appendingPathComponent("\(fileStamp)-stderr.log")
        let resultURL = runDirectory.appendingPathComponent("\(fileStamp)-RESULT.md")
        let requestURL = requestDirectory.appendingPathComponent("\(fileStamp)-HUMAN_REQUEST.md")
        let approvalText = (runtime?.requiresApproval ?? true) ? "Required before any real launch." : "Not required for planning-only preparation."
        let integrationMode = runtime?.integrationMode ?? "planned"
        let notes = runtime?.executionNotes ?? "No runtime profile notes saved yet."

        let content = """
        # Runtime Task Brief — \(task.taskCode)

        Status: Planning only. No external CLI execution has been started.

        ## Project
        - Name: \(project.name)
        - Slug: \(project.slug)
        - Root: `\(project.createdFolderPath)`

        ## Task
        - Code: \(task.taskCode)
        - Title: \(task.title)
        - Milestone: \(task.milestone)
        - Priority: \(task.priority)
        - Assigned Agent: \(task.assignedAgentName)

        ## Runtime
        - Name: \(task.runtimeName)
        - Integration Mode: \(integrationMode)
        - Approval: \(approvalText)
        - Notes: \(notes)

        ## Scope
        - Details: \(task.details)
        - Acceptance Criteria:
        \(task.acceptanceCriteria.isEmpty ? "- No acceptance criteria entered yet." : task.acceptanceCriteria)
        - Dependencies: \(task.dependencies.isEmpty ? "None recorded" : task.dependencies)

        ## Allowed Paths
        - `\(project.createdFolderPath)`

        ## Forbidden Paths
        - Any path outside `\(project.createdFolderPath)`

        ## Planned Output Contract
        - Brief: `\(briefURL.path)`
        - stdout log: `\(stdoutURL.path)`
        - stderr log: `\(stderrURL.path)`
        - result file: `\(resultURL.path)`
        - blocked request file: `\(requestURL.path)`

        ## Safety Gates
        - Human approval before real runtime launch.
        - Destructive actions require a second explicit approval.
        - Refuse launch when allowed/forbidden path scope is missing.
        - Redact secrets before persisting logs.
        """
        try content.write(to: briefURL, atomically: true, encoding: .utf8)

        task.resultSummary = "Runtime brief prepared: \(briefURL.lastPathComponent)"
        task.updatedAt = .now
        try save(task)

        createRunLog(
            task: task,
            status: "prepared",
            summary: "Runtime brief prepared. No external execution started.",
            stage: "prepare-brief",
            artifactPath: briefURL.path
        )
        reloadAll()
        return briefURL.path
    }

    func createRuntimePlanningRequest(taskID: UUID, template: String) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }
        guard let project = projects.first(where: { $0.slug == task.projectSlug }) else {
            return "Project not found"
        }

        let runtime = runtimes.first(where: { $0.name == task.runtimeName })
        let requestTitle: String
        let need: String
        let reason: String
        let recommendedOption: String
        let requestType: String
        let linkedStage: String
        let intendedNextStep: String

        switch template {
        case "auth":
            requestTitle = "Runtime auth needed for \(task.taskCode)"
            need = "Confirm login/auth state for \(task.runtimeName) before any real launch from project `\(project.slug)`.\nAllowed root: `\(project.createdFolderPath)`"
            reason = "Milestone runtime planning reached an auth-sensitive step for \(task.runtimeName)."
            recommendedOption = "Re-auth the runtime outside the app, then return and keep launch approval gated."
            requestType = "auth"
            linkedStage = "open"
            intendedNextStep = "Confirm authentication, then continue planning-only runtime prep."
        case "scope":
            requestTitle = "Scope confirmation needed for \(task.taskCode)"
            need = "Confirm that runtime work must stay inside `\(project.createdFolderPath)` and list any extra allowed files before execution."
            reason = "Runtime brief requires explicit allowed/forbidden path contract before a future launch."
            recommendedOption = "Approve project-root-only scope, or provide an exact additional allowlist."
            requestType = "scope"
            linkedStage = "open"
            intendedNextStep = "Confirm path scope before any launch or artifact generation."
        default:
            requestTitle = "Approval required for \(task.taskCode) runtime launch"
            need = "Approve or reject future runtime launch for task \(task.taskCode) using \(task.runtimeName).\nPlanned scope root: `\(project.createdFolderPath)`"
            reason = "Milestone safety gate requires explicit human approval before real runtime execution."
            recommendedOption = runtime?.requiresApproval == false
                ? "Planning step may proceed now; keep destructive actions separately gated."
                : "Approve planning-only preparation now and require a second approval before any destructive action."
            requestType = "approval"
            linkedStage = "approval"
            intendedNextStep = "Approve the planning gate before future runtime launch."
        }

        let request = createHumanRequest(
            projectSlug: task.projectSlug,
            taskCode: task.taskCode,
            relatedTaskID: task.id,
            title: requestTitle,
            need: need,
            reason: reason,
            priority: task.priority,
            requestType: requestType,
            linkedStage: linkedStage,
            intendedNextStep: intendedNextStep,
            recommendedOption: recommendedOption
        )
        createRunLog(
            task: task,
            status: "request_open",
            summary: requestTitle,
            stage: "request-\(requestType)",
            relatedRequest: request
        )
        reloadAll()
        return requestTitle
    }

    func queueRuntimeApproval(taskID: UUID) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }
        transitionTask(id: taskID, to: "awaiting_approval")
        _ = createRuntimePlanningRequest(taskID: taskID, template: "approval")
        return "Launch approval queued for \(task.taskCode)"
    }

    func markRuntimeLaunchBlocked(taskID: UUID) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }
        transitionTask(id: taskID, to: "launch_blocked")
        _ = createRuntimePlanningRequest(taskID: taskID, template: "scope")
        return "Launch blocked and scope request created for \(task.taskCode)"
    }

    func cancelRuntimePlan(taskID: UUID) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }
        transitionTask(id: taskID, to: "cancelled")
        return "Runtime plan cancelled for \(task.taskCode)"
    }

    func sendTaskToReview(taskID: UUID) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }
        transitionTask(id: taskID, to: "review")
        _ = createStageGateRequest(taskID: taskID, requestType: "review")
        return "Sent \(task.taskCode) to review gate"
    }

    func moveTaskToAudit(taskID: UUID, queueGate: Bool = true) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }
        transitionTask(id: taskID, to: "audit")
        if queueGate {
            _ = createStageGateRequest(taskID: taskID, requestType: "audit")
        }
        return "Moved \(task.taskCode) to audit"
    }

    func createStageGateRequest(taskID: UUID, requestType: String) -> String {
        guard let task = tasks.first(where: { $0.id == taskID }) else {
            return "Task not found"
        }

        if humanRequests.contains(where: {
            ($0.relatedTaskID == taskID || ($0.relatedTaskID == nil && $0.projectSlug == task.projectSlug && $0.taskCode == task.taskCode)) &&
            ($0.requestType ?? "") == requestType &&
            !["resolved", "closed", "cancelled", "answered"].contains($0.status.lowercased())
        }) {
            return "An open \(requestType) gate already exists for \(task.taskCode)"
        }

        let title: String
        let need: String
        let reason: String
        let recommendedOption: String
        let intendedNextStep: String
        let linkedStage: String

        switch requestType {
        case "audit":
            title = "Audit sign-off needed for \(task.taskCode)"
            need = "Review audit readiness for task \(task.title) and decide whether it can be marked done."
            reason = "Task passed review and needs final audit sign-off."
            recommendedOption = "Approve to move task to Done, or request fixes before closure."
            intendedNextStep = "Approving this request moves the task to Done."
            linkedStage = "audit"
        default:
            title = "Review approval needed for \(task.taskCode)"
            need = "Review task output for \(task.title) and decide whether it can move into audit."
            reason = "Execution work completed and entered the review gate."
            recommendedOption = "Approve to move task to Audit, or request fixes before audit."
            intendedNextStep = "Approving this request moves the task to Audit."
            linkedStage = "review"
        }

        let request = createHumanRequest(
            projectSlug: task.projectSlug,
            taskCode: task.taskCode,
            relatedTaskID: task.id,
            title: title,
            need: need,
            reason: reason,
            priority: task.priority,
            requestType: requestType,
            linkedStage: linkedStage,
            intendedNextStep: intendedNextStep,
            recommendedOption: recommendedOption
        )
        createRunLog(
            task: task,
            status: "gate_open",
            summary: title,
            stage: linkedStage,
            relatedRequest: request
        )
        reloadAll()
        return title
    }

    func createAgent(name: String, role: String, goal: String, runtimeName: String, modelName: String, skillNames: String, outputContract: String) {
        let agent = AgentDefinition(
            name: name,
            role: role,
            goal: goal,
            runtimeName: runtimeName,
            modelName: modelName,
            skillNames: skillNames,
            toolsPermission: "file_read,file_write,approval_required",
            memoryScope: "project",
            outputContract: outputContract,
            safetyRules: "Human approval required for destructive actions.",
            createdAt: .now,
            updatedAt: .now
        )
        try? save(agent)
        reloadAll()
    }

    func updateAgent(
        id: UUID,
        name: String,
        role: String,
        goal: String,
        runtimeName: String,
        modelName: String,
        skillNames: String,
        outputContract: String
    ) throws -> AgentDefinition {
        guard var agent = agents.first(where: { $0.id == id }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Agent not found"])
        }

        agent.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.role = role.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.goal = goal.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.runtimeName = runtimeName.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.modelName = modelName.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.skillNames = skillNames.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.outputContract = outputContract.trimmingCharacters(in: .whitespacesAndNewlines)
        agent.updatedAt = .now
        try save(agent)
        reloadAll()
        return agent
    }

    func deleteAgents(_ items: [AgentDefinition]) {
        items.forEach { try? delete($0) }
        reloadAll()
    }

    func createSkill(name: String, type: String, instruction: String, workflow: String, checklist: String, outputContract: String, requiredTools: String) {
        let skill = SkillDefinition(
            name: name,
            type: type,
            instruction: instruction,
            workflow: workflow,
            checklist: checklist,
            outputContract: outputContract,
            requiredTools: requiredTools,
            createdAt: .now,
            updatedAt: .now
        )
        try? save(skill)
        reloadAll()
    }

    func updateSkill(
        id: UUID,
        name: String,
        type: String,
        instruction: String,
        workflow: String,
        checklist: String,
        outputContract: String,
        requiredTools: String
    ) throws -> SkillDefinition {
        guard var skill = skills.first(where: { $0.id == id }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Skill not found"])
        }

        skill.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.type = type.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.instruction = instruction.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.workflow = workflow.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.checklist = checklist.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.outputContract = outputContract.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.requiredTools = requiredTools.trimmingCharacters(in: .whitespacesAndNewlines)
        skill.updatedAt = .now
        try save(skill)
        reloadAll()
        return skill
    }

    func deleteSkills(_ items: [SkillDefinition]) {
        items.forEach { try? delete($0) }
        reloadAll()
    }

    func createTeam(name: String, purpose: String, leadAgentName: String, memberAgentNames: String, workflow: String, reviewRules: String, runtimePreference: String, projectSlug: String) {
        let team = TeamDefinition(
            name: name,
            purpose: purpose,
            leadAgentName: leadAgentName,
            memberAgentNames: memberAgentNames,
            workflow: workflow,
            reviewRules: reviewRules,
            runtimePreference: runtimePreference,
            projectSlug: projectSlug,
            isTemplate: projectSlug == "template",
            createdAt: .now,
            updatedAt: .now
        )
        try? save(team)
        reloadAll()
    }

    func updateTeam(
        id: UUID,
        name: String,
        purpose: String,
        leadAgentName: String,
        memberAgentNames: String,
        workflow: String,
        reviewRules: String,
        runtimePreference: String,
        projectSlug: String
    ) throws -> TeamDefinition {
        guard var team = teams.first(where: { $0.id == id }) else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 404, userInfo: [NSLocalizedDescriptionKey: "Team not found"])
        }

        team.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        team.purpose = purpose.trimmingCharacters(in: .whitespacesAndNewlines)
        team.leadAgentName = leadAgentName.trimmingCharacters(in: .whitespacesAndNewlines)
        team.memberAgentNames = memberAgentNames.trimmingCharacters(in: .whitespacesAndNewlines)
        team.workflow = workflow.trimmingCharacters(in: .whitespacesAndNewlines)
        team.reviewRules = reviewRules.trimmingCharacters(in: .whitespacesAndNewlines)
        team.runtimePreference = runtimePreference.trimmingCharacters(in: .whitespacesAndNewlines)
        team.projectSlug = projectSlug.trimmingCharacters(in: .whitespacesAndNewlines)
        team.isTemplate = team.projectSlug == "template"
        team.updatedAt = .now
        try save(team)
        reloadAll()
        return team
    }

    func deleteTeams(_ items: [TeamDefinition]) {
        items.forEach { try? delete($0) }
        reloadAll()
    }

    func createRuntime(name: String, runtimeType: String, integrationMode: String, executionNotes: String, requiresApproval: Bool) {
        let runtime = RuntimeProfile(
            name: name,
            runtimeType: runtimeType,
            integrationMode: integrationMode,
            executionNotes: executionNotes,
            requiresApproval: requiresApproval,
            isDefault: false,
            createdAt: .now,
            updatedAt: .now
        )
        try? save(runtime)
        reloadAll()
    }

    func deleteRuntimes(_ items: [RuntimeProfile]) {
        items.forEach { try? delete($0) }
        reloadAll()
    }

    func setDefaultRuntime(id: UUID, isDefault: Bool) {
        for var runtime in runtimes {
            runtime.isDefault = runtime.id == id ? isDefault : false
            runtime.updatedAt = .now
            try? save(runtime)
        }
        reloadAll()
    }

    func createTask(projectSlug: String, taskCode: String, milestone: String, title: String, details: String, priority: String, assignedAgentName: String, runtimeName: String, acceptanceCriteria: String, dependencies: String) {
        let task = StudioTask(
            projectSlug: projectSlug,
            taskCode: taskCode,
            milestone: milestone,
            title: title,
            details: details,
            priority: priority,
            status: "todo",
            assignedAgentName: assignedAgentName,
            runtimeName: runtimeName,
            acceptanceCriteria: acceptanceCriteria,
            dependencies: dependencies,
            resultSummary: "",
            createdAt: .now,
            updatedAt: .now
        )
        try? save(task)
        reloadAll()
    }

    func seedInitialTaskBoard(for project: StudioProject, advanceProjectStage: Bool = false) {
        let alreadySeeded = tasks.contains { $0.projectSlug == project.slug }
        guard !alreadySeeded else { return }

        let defaultAgent = agents.first?.name ?? "PM Agent"
        let taskList = [
            StudioTask(projectSlug: project.slug, taskCode: "T1", milestone: "App Shell", title: "Confirm project scaffold and local workspace", details: "Create folder structure, persist project record, and verify dashboard visibility.", priority: "high", status: "todo", assignedAgentName: defaultAgent, runtimeName: "Mock Local Runtime", acceptanceCriteria: "Project folder exists\nProject visible in dashboard", dependencies: "", resultSummary: "", createdAt: .now, updatedAt: .now),
            StudioTask(projectSlug: project.slug, taskCode: "T2", milestone: "PRD Context", title: "Import PRD and generate normalized markdown", details: "Copy original PRD, save normalized markdown, and create analysis placeholder.", priority: "high", status: "todo", assignedAgentName: "Product Analyst Agent", runtimeName: "Mock Local Runtime", acceptanceCriteria: "Original PRD copied\nPRD_NORMALIZED.md exists\nPRD_ANALYSIS.md exists", dependencies: "T1", resultSummary: "", createdAt: .now, updatedAt: .now),
            StudioTask(projectSlug: project.slug, taskCode: "T3", milestone: "Team Setup", title: "Assemble agent team and runtime map", details: "Choose team lead, members, and runtime preferences.", priority: "medium", status: "todo", assignedAgentName: "PM Agent", runtimeName: "Mock Local Runtime", acceptanceCriteria: "Team exists\nLead assigned\nRuntimes mapped", dependencies: "T1,T2", resultSummary: "", createdAt: .now, updatedAt: .now),
            StudioTask(projectSlug: project.slug, taskCode: "T4", milestone: "Delivery Loop", title: "Run manual mock execution and review loop", details: "Move one task through running, review, audit, and demo readiness manually.", priority: "medium", status: "todo", assignedAgentName: "QA Agent", runtimeName: "Mock Local Runtime", acceptanceCriteria: "Run log exists\nReview or audit state reached", dependencies: "T3", resultSummary: "", createdAt: .now, updatedAt: .now)
        ]
        taskList.forEach { try? save($0) }
        if advanceProjectStage {
            updateProjectMetadata(id: project.id, status: "task_generated", milestone: "Task Board")
        } else {
            reloadAll()
        }
    }

    func transitionTask(id: UUID, to newStatus: String) {
        guard var task = tasks.first(where: { $0.id == id }) else { return }
        task.status = newStatus
        task.updatedAt = .now

        switch newStatus {
        case "awaiting_approval":
            task.resultSummary = "Runtime plan queued for launch approval."
            createRunLog(task: task, status: "awaiting_approval", summary: "Waiting for pre-launch approval.", stage: "approval-gate")
        case "launch_blocked":
            task.resultSummary = "Runtime launch blocked pending human decision."
            createRunLog(task: task, status: "launch_blocked", summary: "Launch blocked before execution.", stage: "launch-blocked")
        case "running":
            task.resultSummary = "Mock execution started."
            createRunLog(task: task, status: "running", summary: "Mock run started for \(task.title)", stage: "in_progress")
        case "review":
            task.resultSummary = "Implementation draft completed and waiting for review gate."
            createRunLog(task: task, status: "review", summary: "Task moved to review.", stage: "review")
        case "audit":
            task.resultSummary = "Review passed. Awaiting audit gate."
            createRunLog(task: task, status: "audit", summary: "Task moved to audit.", stage: "audit")
        case "done":
            task.resultSummary = "Audit passed. Task complete."
            createRunLog(task: task, status: "done", summary: "Audit passed.", stage: "done")
        case "need_fix":
            task.resultSummary = "Review or audit requested revisions."
            createRunLog(task: task, status: "need_fix", summary: "Task returned for fixes.", stage: "in_progress", errorSummary: "Additional revisions requested before the next gate.")
        case "blocked":
            task.resultSummary = "Waiting for human decision."
            createRunLog(task: task, status: "blocked", summary: "Task blocked pending human input.", stage: "open")
            _ = createHumanRequest(
                projectSlug: task.projectSlug,
                taskCode: task.taskCode,
                relatedTaskID: task.id,
                title: "Decision required for \(task.taskCode)",
                need: "Review scope, acceptance criteria, or external asset before continuing task \(task.title).",
                reason: "Manual checkpoint triggered from mock task loop.",
                priority: task.priority,
                requestType: "blocker",
                linkedStage: primaryStage(for: task),
                intendedNextStep: "Provide clarification or approval so work can resume.",
                recommendedOption: "Approve the next step or provide updated constraints."
            )
        case "cancelled":
            task.resultSummary = "Runtime plan cancelled before execution."
            createRunLog(task: task, status: "cancelled", summary: "Task plan cancelled.", stage: "open")
        default:
            task.resultSummary = "Reset to backlog."
            createRunLog(task: task, status: newStatus, summary: "Task reset to backlog.", stage: "open")
        }

        try? save(task)
        reloadAll()
    }

    @discardableResult
    func createHumanRequest(
        projectSlug: String,
        taskCode: String,
        relatedTaskID: UUID? = nil,
        title: String,
        need: String,
        reason: String,
        priority: String,
        requestType: String = "blocker",
        linkedStage: String? = nil,
        intendedNextStep: String? = nil,
        recommendedOption: String
    ) -> HumanRequestItem {
        let request = HumanRequestItem(
            projectSlug: projectSlug,
            taskCode: taskCode,
            relatedTaskID: relatedTaskID,
            title: title,
            need: need,
            reason: reason,
            priority: priority,
            isBlocking: true,
            status: "open",
            requestType: requestType,
            linkedStage: linkedStage,
            intendedNextStep: intendedNextStep,
            recommendedOption: recommendedOption,
            userResponse: "",
            createdAt: .now,
            updatedAt: .now
        )
        try? save(request)
        reloadAll()
        return request
    }

    func deleteHumanRequests(_ items: [HumanRequestItem]) {
        items.forEach { try? delete($0) }
        reloadAll()
    }

    func updateHumanRequestStatus(id: UUID, status: String) {
        guard var request = humanRequests.first(where: { $0.id == id }) else { return }
        request.status = status
        request.updatedAt = .now
        try? save(request)
        reloadAll()
    }

    func updateHumanRequestResponse(id: UUID, response: String) {
        guard var request = humanRequests.first(where: { $0.id == id }) else { return }
        request.userResponse = response
        request.updatedAt = .now
        try? save(request)
        reloadAll()
    }

    func resolveHumanRequest(id: UUID, response: String, status: String) {
        guard var request = humanRequests.first(where: { $0.id == id }) else { return }
        request.status = status
        request.userResponse = response
        request.updatedAt = .now
        try? save(request)
        reloadAll()
    }

    func approveHumanRequest(id: UUID, response: String) {
        guard var request = humanRequests.first(where: { $0.id == id }) else { return }
        request.status = "resolved"
        request.userResponse = response
        request.updatedAt = .now
        try? save(request)

        if let task = linkedTask(for: request) {
            switch request.requestType ?? "blocker" {
            case "review":
                _ = moveTaskToAudit(taskID: task.id, queueGate: true)
            case "audit":
                transitionTask(id: task.id, to: "done")
            case "approval", "scope", "auth", "blocker":
                transitionTask(id: task.id, to: "running")
            default:
                transitionTask(id: task.id, to: "running")
            }
        }

        reloadAll()
    }

    func requestFixForHumanRequest(id: UUID, response: String) {
        guard var request = humanRequests.first(where: { $0.id == id }) else { return }
        request.status = "answered"
        request.userResponse = response
        request.updatedAt = .now
        try? save(request)

        if let task = linkedTask(for: request) {
            transitionTask(id: task.id, to: "need_fix")
        }

        reloadAll()
    }

    func keepHumanRequestOpen(id: UUID, response: String, status: String = "answered") {
        guard var request = humanRequests.first(where: { $0.id == id }) else { return }
        request.status = status
        request.userResponse = response
        request.updatedAt = .now
        try? save(request)
        reloadAll()
    }

    func primaryStage(for task: StudioTask) -> String {
        switch task.status {
        case "review":
            return "review"
        case "audit":
            return "audit"
        case "done":
            return "done"
        case "running", "need_fix":
            return "in_progress"
        default:
            return "open"
        }
    }

    func openRequests(for task: StudioTask) -> [HumanRequestItem] {
        humanRequests.filter {
            ($0.relatedTaskID == task.id || ($0.relatedTaskID == nil && $0.projectSlug == task.projectSlug && $0.taskCode == task.taskCode)) &&
            !["resolved", "closed", "cancelled", "answered"].contains($0.status.lowercased())
        }
    }

    func latestRunLog(for task: StudioTask) -> TaskRunLog? {
        runLogs.first(where: { $0.projectSlug == task.projectSlug && $0.taskCode == task.taskCode })
    }

    func taskStatusBadge(for task: StudioTask) -> String? {
        switch task.status {
        case "assigned":
            return "Assigned"
        case "awaiting_approval":
            return "Approval Pending"
        case "launch_blocked":
            return "Launch Blocked"
        case "blocked":
            return "Blocked"
        case "need_fix":
            return "Need Fix"
        case "cancelled":
            return "Cancelled"
        case "running":
            return "Running"
        default:
            return nil
        }
    }

    func unresolvedRequestCount(for projectSlug: String) -> Int {
        humanRequests.filter {
            $0.projectSlug == projectSlug && !["resolved", "closed", "cancelled", "answered"].contains($0.status.lowercased())
        }.count
    }

    private func linkedTask(for request: HumanRequestItem) -> StudioTask? {
        if let relatedTaskID = request.relatedTaskID,
           let task = tasks.first(where: { $0.id == relatedTaskID }) {
            return task
        }

        return tasks.first {
            $0.projectSlug == request.projectSlug && $0.taskCode == request.taskCode
        }
    }

    func createDemoItem(projectSlug: String, itemType: String, title: String, details: String, owner: String, artifactPath: String? = nil) {
        let item = DemoHandoffItem(
            projectSlug: projectSlug,
            itemType: itemType,
            title: title,
            details: details,
            status: "pending",
            owner: owner,
            artifactPath: artifactPath,
            createdAt: .now,
            updatedAt: .now
        )
        try? save(item)
        reloadAll()
    }

    func seedDemoAndHandoffChecklist(for project: StudioProject) {
        let hasItems = demoItems.contains { $0.projectSlug == project.slug }
        guard !hasItems else { return }

        let items = [
            DemoHandoffItem(projectSlug: project.slug, itemType: "demo", title: "Demo checklist", details: "Confirm dashboard, PRD import, task board, and human request inbox flows.", status: "pending", owner: "Demo Agent", artifactPath: nil, createdAt: .now, updatedAt: .now),
            DemoHandoffItem(projectSlug: project.slug, itemType: "demo", title: "Demo script", details: "Prepare short walkthrough from project creation to manual task loop.", status: "pending", owner: "Demo Agent", artifactPath: nil, createdAt: .now, updatedAt: .now),
            DemoHandoffItem(projectSlug: project.slug, itemType: "handoff", title: "Known limitations", details: "Document that runtime execution is mock/manual in V1.", status: "pending", owner: "Documentation Agent", artifactPath: nil, createdAt: .now, updatedAt: .now),
            DemoHandoffItem(projectSlug: project.slug, itemType: "handoff", title: "Closure package", details: "Collect project notes, PRD paths, run logs, and next-step plan.", status: "pending", owner: "Handoff Agent", artifactPath: nil, createdAt: .now, updatedAt: .now)
        ]
        items.forEach { try? save($0) }
        reloadAll()
    }

    func deleteDemoItems(_ items: [DemoHandoffItem]) {
        items.forEach { try? delete($0) }
        reloadAll()
    }

    func updateDemoItemStatus(id: UUID, status: String) {
        guard var item = demoItems.first(where: { $0.id == id }) else { return }
        item.status = status
        item.updatedAt = .now
        try? save(item)
        reloadAll()
    }

    private func createRunLog(
        task: StudioTask,
        status: String,
        summary: String,
        stage: String,
        artifactPath: String? = nil,
        relatedRequest: HumanRequestItem? = nil,
        errorSummary: String? = nil
    ) {
        var sections = [
            "[\(DateFormatter.studioTimestamp.string(from: .now))] Stage: \(stage)",
            "Task: \(task.taskCode) - \(task.title)",
            "Project: \(task.projectSlug)",
            "Runtime: \(task.runtimeName)"
        ]

        if let artifactPath, !artifactPath.isEmpty {
            sections.append("Artifact: \(artifactPath)")
        }
        if let relatedRequest {
            sections.append("Related Request: \(relatedRequest.title)")
        }
        if let errorSummary, !errorSummary.isEmpty {
            sections.append("Error: \(errorSummary)")
        }

        sections.append("")
        sections.append("This is a manual/mock task loop entry for V1.")
        sections.append("No autonomous agent execution has been performed.")

        let log = TaskRunLog(
            projectSlug: task.projectSlug,
            taskCode: task.taskCode,
            taskTitle: task.title,
            runtimeName: task.runtimeName,
            status: status,
            summary: summary,
            logText: sections.joined(separator: "\n"),
            stage: stage,
            artifactPath: artifactPath,
            relatedRequestID: relatedRequest?.id,
            relatedRequestTitle: relatedRequest?.title,
            errorSummary: errorSummary,
            startedAt: .now,
            endedAt: .now
        )
        try? save(log)
    }

    private func updateProjectMetadata(id: UUID, status: String, milestone: String) {
        guard var project = projects.first(where: { $0.id == id }) else { return }
        project.status = status
        project.currentMilestone = milestone
        project.updatedAt = .now
        try? save(project)
    }

    private func milestoneLabel(for status: String, fallback: String) -> String {
        switch status {
        case "draft":
            return "Project Setup"
        case "prd_uploaded", "prd_analyzed":
            return "PRD Context"
        case "team_selected":
            return "Team Builder"
        case "task_generated", "in_progress", "review", "revision":
            return "Task Delivery"
        case "demo_ready", "demo_sent", "handoff_ready":
            return "Demo / Handoff Readiness"
        case "closed":
            return "Closed"
        case "archived":
            return "Archived"
        default:
            return fallback
        }
    }

    private func artifactDirectory(for project: StudioProject, folderName: String) throws -> URL {
        guard !project.createdFolderPath.isEmpty else {
            throw NSError(domain: "HeadOfficeAgentStudio", code: 1, userInfo: [NSLocalizedDescriptionKey: "Project folder has not been created yet."])
        }

        let directory = URL(fileURLWithPath: project.createdFolderPath, isDirectory: true)
            .appendingPathComponent(folderName, isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }

    private func blockingRequests(for projectSlug: String) -> [HumanRequestItem] {
        humanRequests.filter {
            $0.projectSlug == projectSlug &&
            $0.isBlocking &&
            !["resolved", "closed", "cancelled", "answered"].contains($0.status.lowercased())
        }
    }

    private func upsertDemoItem(projectSlug: String, itemType: String, title: String, details: String, owner: String, artifactPath: String?, status: String) {
        if var existing = demoItems.first(where: { $0.projectSlug == projectSlug && $0.title == title }) {
            existing.itemType = itemType
            existing.details = details
            existing.owner = owner
            existing.artifactPath = artifactPath
            existing.status = status
            existing.updatedAt = .now
            try? save(existing)
            return
        }

        let item = DemoHandoffItem(
            projectSlug: projectSlug,
            itemType: itemType,
            title: title,
            details: details,
            status: status,
            owner: owner,
            artifactPath: artifactPath,
            createdAt: .now,
            updatedAt: .now
        )
        try? save(item)
    }

    private func seedIfNeeded() throws {
        if runtimes.isEmpty {
            let runtimeSeeds = [
                RuntimeProfile(name: "Mock Local Runtime", runtimeType: "mock", integrationMode: "manual", executionNotes: "Default V1 runtime for manual/mock task loop.", requiresApproval: true, isDefault: true, createdAt: .now, updatedAt: .now),
                RuntimeProfile(name: "Codex CLI", runtimeType: "coding-agent", integrationMode: "planned", executionNotes: "Placeholder only. Real integration after app shell milestone.", requiresApproval: true, isDefault: false, createdAt: .now, updatedAt: .now),
                RuntimeProfile(name: "Claude Code", runtimeType: "coding-agent", integrationMode: "planned", executionNotes: "Manual use outside the app for now.", requiresApproval: true, isDefault: false, createdAt: .now, updatedAt: .now),
                RuntimeProfile(name: "Gemini CLI", runtimeType: "analysis-agent", integrationMode: "planned", executionNotes: "Runtime Manager tracks readiness only in V1.", requiresApproval: true, isDefault: false, createdAt: .now, updatedAt: .now)
            ]
            try runtimeSeeds.forEach { try save($0) }
        }

        if agents.isEmpty {
            let agentSeeds = [
                ("PM Agent", "Project Manager", "Coordinate milestones, scope, and approvals."),
                ("Product Analyst Agent", "Product Analyst", "Turn PRD scope into modules, questions, and deliverables."),
                ("UX / Sitemap Agent", "UX Planner", "Map screens, flows, and information architecture."),
                ("Backend Agent", "Backend Developer", "Design backend logic and service contracts."),
                ("Frontend Agent", "Frontend Developer", "Implement native UI screens and user flow."),
                ("Database Architect Agent", "Database Architect", "Define entities, storage, and data integrity rules."),
                ("Integration Agent", "Integration Engineer", "Connect modules and orchestrate workflow handoffs."),
                ("QA Agent", "Quality Assurance", "Verify expected behavior with evidence."),
                ("Audit Agent", "Auditor", "Check scope, safety, and sign-off readiness."),
                ("Documentation Agent", "Technical Writer", "Prepare runbooks, notes, and handoff artifacts."),
                ("Demo Agent", "Demo Specialist", "Prepare demos and client walkthroughs."),
                ("Handoff Agent", "Handoff Manager", "Prepare final package and closure materials.")
            ]
            for item in agentSeeds {
                try save(AgentDefinition(name: item.0, role: item.1, goal: item.2, runtimeName: "Mock Local Runtime", modelName: "mock-v1", skillNames: "scope-analysis, review-loop, file-transparency", toolsPermission: "file_read,file_write,approval_required", memoryScope: "project", outputContract: "TASK_RESULT.md, CHANGED_FILES.md, RISK_NOTES.md", safetyRules: "No deployment or destructive edits without human approval.", createdAt: .now, updatedAt: .now))
            }
        }

        if skills.isEmpty {
            let skillSeeds = [
                ("PRD Writer", "output"),
                ("Scope Analyzer", "workflow"),
                ("Task Breakdown", "workflow"),
                ("Supabase Schema Designer", "tool"),
                ("RLS Policy Reviewer", "review"),
                ("API Design", "tool"),
                ("Frontend Component Planner", "workflow"),
                ("UX Flow Mapping", "workflow"),
                ("QA Checklist", "review"),
                ("Security Audit", "audit"),
                ("Demo Script Writer", "output"),
                ("Handoff Document Writer", "output"),
                ("Fastwork Proposal Writer", "output"),
                ("DataClaw Research Scanner", "tool"),
                ("Inventory System Analyst", "workflow"),
                ("HR Payroll Analyst", "workflow")
            ]
            for item in skillSeeds {
                try save(SkillDefinition(name: item.0, type: item.1, instruction: "Reusable capability scaffold for \(item.0).", workflow: "Read context → produce structured output → hand off to review.", checklist: "Scope confirmed\nAssumptions logged\nOutput saved to file", outputContract: "Markdown summary + risks + next steps", requiredTools: "SQLite store, local files, manual approval gate", createdAt: .now, updatedAt: .now))
            }
        }

        if teams.isEmpty {
            let teamSeeds = [
                TeamDefinition(name: "HR Payroll Team", purpose: "Handle payroll, policy, and employee workflow delivery.", leadAgentName: "PM Agent", memberAgentNames: "Product Analyst Agent, Backend Agent, QA Agent", workflow: "Analyze PRD → Build → Review → Audit", reviewRules: "PM approval before audit close.", runtimePreference: "Mock Local Runtime", projectSlug: "template", isTemplate: true, createdAt: .now, updatedAt: .now),
                TeamDefinition(name: "Inventory System Team", purpose: "Deliver internal operations systems with clear review gates.", leadAgentName: "PM Agent", memberAgentNames: "Frontend Agent, Backend Agent, Database Architect Agent, QA Agent", workflow: "Plan → Implement → Review → Audit", reviewRules: "Audit must pass before handoff.", runtimePreference: "Mock Local Runtime", projectSlug: "template", isTemplate: true, createdAt: .now, updatedAt: .now),
                TeamDefinition(name: "AI Content System Team", purpose: "Build AI-assisted content workflows with human approval.", leadAgentName: "PM Agent", memberAgentNames: "UX / Sitemap Agent, Integration Agent, Documentation Agent", workflow: "Scope → Prototype → Review → Demo", reviewRules: "Human approval before automation.", runtimePreference: "Mock Local Runtime", projectSlug: "template", isTemplate: true, createdAt: .now, updatedAt: .now)
            ]
            try teamSeeds.forEach { try save($0) }
        }

        reloadAll()
    }

    private func save<Record: StudioRecord>(_ record: Record) throws {
        try database?.save(record)
    }

    private func delete<Record: StudioRecord>(_ record: Record) throws {
        try database?.delete(record)
    }
}

extension DateFormatter {
    static let studioDate: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .none
        return formatter
    }()

    static let studioTimestamp: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .medium
        return formatter
    }()

    static let studioFileStamp: DateFormatter = {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd_HHmmss"
        return formatter
    }()
}
