export const imageGenerationConnector = {
  provider: 'OpenAI Images API',
  defaultModel: 'gpt-image-2',
  lockedSnapshot: 'gpt-image-2-2026-04-21',
  thaiTextRule: 'Generate visual/background only; Thai text must be overlaid by the app composer.',
};

export const agentBlueprints = [
  {
    name: 'Agent Orchestrator',
    purpose: 'Controls queue order, assigns work to the correct specialist agent, and prevents publishing before approval.',
    model: 'GPT-5.4-Mini',
    provider: 'Codex runtime',
    workload: 'Routing',
    runs: 156,
    activity: 86,
  },
  {
    name: 'Content Strategy Agent',
    purpose: 'Turns user requirements into topic anchors, content plans, draft structure, and platform-specific copy direction.',
    model: 'GPT-5.4',
    provider: 'Codex runtime',
    workload: 'Planning + drafting',
    runs: 54,
    activity: 80,
  },
  {
    name: 'RAG Research Agent',
    purpose: 'Searches Knowledge Base, Google Drive, Obsidian, official links, and approved web sources before drafting.',
    model: 'GPT-5.4',
    provider: 'Codex runtime',
    workload: 'Retrieving',
    runs: 91,
    activity: 88,
  },
  {
    name: 'Brand Memory Agent',
    purpose: 'Learns approved writing style, recurring edits, preferred wording, forbidden phrasing, and user-specific tone patterns.',
    model: 'GPT-5.4-Mini',
    provider: 'Codex runtime',
    workload: 'Learning',
    runs: 24,
    activity: 46,
  },
  {
    name: 'Legal Compliance Agent',
    purpose: 'Checks legal claims, prohibited wording, citations, and professional ethics rules.',
    model: 'GPT-5.5',
    provider: 'Codex runtime',
    workload: 'Reviewing',
    runs: 64,
    activity: 82,
  },
  {
    name: 'Tax & Accounting Agent',
    purpose: 'Reviews tax/accounting accuracy, deadlines, document requirements, and risk language.',
    model: 'GPT-5.4',
    provider: 'Codex runtime',
    workload: 'Idle',
    runs: 42,
    activity: 51,
  },
  {
    name: 'Multilingual Localization Agent',
    purpose: 'Translates and adapts Thai, English, Chinese, and Japanese content while preserving meaning.',
    model: 'GPT-5.4-Mini',
    provider: 'Codex runtime',
    workload: 'Translating',
    runs: 118,
    activity: 92,
  },
  {
    name: 'Image & Layout Agent',
    purpose: `Converts final text into visual brief, layout constraints, image prompt, and sends generation to ${imageGenerationConnector.defaultModel}. Thai text is overlaid by the app composer.`,
    model: 'GPT-5.4',
    provider: 'Codex runtime / OpenAI Images API',
    workload: 'Idle',
    runs: 27,
    activity: 36,
  },
  {
    name: 'Publishing Agent',
    purpose: 'Queues approved posts to LinkedIn, Facebook, WordPress, Buffer, and newsletters while recording retry/failure logs.',
    model: 'GPT-5.4-Mini',
    provider: 'Codex runtime',
    workload: 'Queued',
    runs: 75,
    activity: 69,
  },
  {
    name: 'Analytics Insight Agent',
    purpose: 'Summarizes reach, engagement, clicks, language performance, and topic trends.',
    model: 'GPT-5.4-Mini',
    provider: 'Codex runtime',
    workload: 'Reporting',
    runs: 33,
    activity: 44,
  },
];

export const agentOperatingWorkflow = [
  {
    step: '1',
    stage: 'Queue orchestration',
    agent: 'Agent Orchestrator',
    model: 'GPT-5.4-Mini',
    output: 'Validated queue item, selected route, ownership, SLA, and next agent assignment',
    handoff: 'Creates a specialist task card and blocks invalid transitions',
  },
  {
    step: '2',
    stage: 'Brief intake',
    agent: 'Content Strategy Agent',
    model: 'GPT-5.4',
    output: 'Topic plan, post count, audience, platform direction',
    handoff: 'Creates job package for RAG Research Agent',
  },
  {
    step: '3',
    stage: 'Source grounding',
    agent: 'RAG Research Agent',
    model: 'GPT-5.4',
    output: 'Cited source pack from Knowledge Base, Google Drive, Obsidian, and official links',
    handoff: 'Blocks generation if no citation exists',
  },
  {
    step: '4',
    stage: 'Style memory lookup',
    agent: 'Brand Memory Agent',
    model: 'GPT-5.4-Mini',
    output: 'Approved tone, recurring user edits, preferred phrases, and banned wording for this topic/audience',
    handoff: 'Injects memory constraints into text generation and localization prompts',
  },
  {
    step: '5',
    stage: 'Text generation',
    agent: 'Content Strategy Agent',
    model: 'GPT-5.4',
    output: 'Thai-first copy package with translation-ready structure',
    handoff: 'Sends text package to Localization, Image/Layout, and Compliance queues',
  },
  {
    step: '6',
    stage: 'Localization',
    agent: 'Multilingual Localization Agent',
    model: 'GPT-5.4-Mini',
    output: 'Thai, English, Chinese, and Japanese variants with legal meaning preserved',
    handoff: 'Sends localized variants to Compliance and Review Queue package',
  },
  {
    step: '7',
    stage: 'Image + layout',
    agent: 'Image & Layout Agent',
    model: 'GPT-5.4',
    output: 'Visual brief, generated image asset selection, carousel/grid/single layout',
    handoff: 'Attaches assets to Review Queue package',
  },
  {
    step: '8',
    stage: 'Legal compliance',
    agent: 'Legal Compliance Agent',
    model: 'GPT-5.5',
    output: 'Citation, prohibited claim, legal/tax/accounting risk report',
    handoff: 'Routes legal risk result to Review Queue or revision queue',
  },
  {
    step: '9',
    stage: 'Tax/accounting review',
    agent: 'Tax & Accounting Agent',
    model: 'GPT-5.4',
    output: 'Tax/accounting accuracy, deadline, document, and risk wording report',
    handoff: 'Routes tax/accounting result to Review Queue or revision queue',
  },
  {
    step: '10',
    stage: 'Human review gate',
    agent: 'Review Queue',
    model: 'Human-in-the-loop',
    output: 'Approve, Reject, Regenerate, or Auto Queue decision',
    handoff: 'Only approved work can move to Publishing Agent',
  },
  {
    step: '11',
    stage: 'Queue + post',
    agent: 'Publishing Agent',
    model: 'GPT-5.4-Mini',
    output: 'Publishing queue status, sync result, failure log',
    handoff: 'Writes lifecycle event and sends results to Analytics Insight Agent',
  },
  {
    step: '12',
    stage: 'Performance learning',
    agent: 'Analytics Insight Agent',
    model: 'GPT-5.4-Mini',
    output: 'Performance summary, language insight, topic trend, and memory suggestions',
    handoff: 'Sends approved learning signals to Brand Memory Agent and planning signals to Content Strategy Agent',
  },
];

export const modelCatalog: Record<string, string[]> = {
  'Codex runtime': ['GPT-5.4-Mini', 'GPT-5.4', 'GPT-5.5'],
};

export const hiddenCodexModels = ['GPT-5.3-Codex-Spark'];

export const agentRoutingRows = [
  {
    task: 'Topic planning',
    agent: 'Content Strategy Agent',
    model: 'GPT-5.4',
    trigger: 'New weekly campaign, empty calendar slot, or service coverage gap',
    rule: 'Use fast planning model first, escalate only when legal risk is detected.',
    risk: 'Low',
  },
  {
    task: 'Source search / RAG',
    agent: 'RAG Research Agent',
    model: 'GPT-5.4',
    trigger: 'User asks AI to cite law, tax notice, internal policy, or client-specific rule',
    rule: 'Return cited sources only. If no source is found, block generation and request upload.',
    risk: 'Medium',
  },
  {
    task: 'Draft generation',
    agent: 'Content Strategy Agent',
    model: 'GPT-5.4',
    trigger: 'Create Post reaches Generation step after sources are selected',
    rule: 'Generate Thai first, then prepare translation-ready structure and image brief.',
    risk: 'Medium',
  },
  {
    task: 'Legal / tax review',
    agent: 'Legal Compliance Agent',
    model: 'GPT-5.5',
    trigger: 'Any claim about tax savings, legal outcome, visa result, PDPA, or labor law',
    rule: 'Always require citation, flag prohibited promises, and route high-risk items to human review.',
    risk: 'High',
  },
  {
    task: 'Localization',
    agent: 'Multilingual Localization Agent',
    model: 'GPT-5.4-Mini',
    trigger: 'Multi-language generation for English, Chinese, or Japanese',
    rule: 'Preserve legal meaning, compare translation drift, and keep audience-specific tone.',
    risk: 'Medium',
  },
  {
    task: 'Image + layout',
    agent: 'Image & Layout Agent',
    model: 'GPT-5.4',
    trigger: 'Text package is ready and visual brief can be derived from final copy',
    rule: 'Create image direction after text generation, then attach selected assets to Review Queue.',
    risk: 'Medium',
  },
  {
    task: 'Publishing',
    agent: 'Publishing Agent',
    model: 'GPT-5.4-Mini',
    trigger: 'Approved content is queued or Publish Now is clicked',
    rule: 'Publish only approved content, check platform token, then log every sync result.',
    risk: 'Medium',
  },
  {
    task: 'Analytics insight',
    agent: 'Analytics Insight Agent',
    model: 'GPT-5.4-Mini',
    trigger: 'Weekly report, campaign review, or topic performance comparison',
    rule: 'Summarize trend, winner topic, language performance, and next recommended action.',
    risk: 'Low',
  },
];

export const agentEscalationRules = [
  'High-risk legal/tax claims always go to Review Queue before publishing.',
  'If RAG has no citation, content generation is blocked instead of guessed.',
  'Fast/low-cost models handle planning, drafts, publishing logs, and analytics summaries.',
  'Stronger models handle compliance, source reasoning, and cross-language meaning checks.',
];
