export const contentCategories = [
  { name: 'All Content', count: 128 },
  { name: 'Tax', count: 31 },
  { name: 'Visa', count: 18 },
  { name: 'Labor Law', count: 22 },
  { name: 'Corporate Law', count: 27 },
  { name: 'Accounting', count: 19 },
  { name: 'PDPA', count: 11 },
];

export const libraryItems = [
  {
    id: 'LIB-301',
    title: 'PDPA Compliance Checklist for Thai Businesses',
    category: 'PDPA',
    language: 'TH / EN',
    status: 'Approved',
    updated: 'Updated 2 days ago',
    assets: 6,
    reuse: 'High',
  },
  {
    id: 'LIB-302',
    title: 'VAT Filing Mistakes That Cost SMEs Money',
    category: 'Tax',
    language: 'TH',
    status: 'Needs update',
    updated: 'Updated 3 months ago',
    assets: 4,
    reuse: 'Medium',
  },
  {
    id: 'LIB-303',
    title: 'Hiring Your First Employee in Thailand',
    category: 'Labor Law',
    language: 'TH / EN',
    status: 'Approved',
    updated: 'Updated 1 week ago',
    assets: 5,
    reuse: 'High',
  },
  {
    id: 'LIB-304',
    title: 'Visa Options for Foreign Directors',
    category: 'Visa',
    language: 'EN / JP',
    status: 'Draft',
    updated: 'Updated yesterday',
    assets: 3,
    reuse: 'Low',
  },
  {
    id: 'LIB-305',
    title: 'Company Registration Guide for Foreign Investors',
    category: 'Corporate Law',
    language: 'EN / ZH',
    status: 'Approved',
    updated: 'Updated 5 days ago',
    assets: 8,
    reuse: 'High',
  },
];
